touch ~/.notes/alabama
touch ~/.notes/alaska
touch ~/.notes/arizona
touch ~/.notes/arkansas
touch ~/.notes/california
touch ~/.notes/colorado
touch ~/.notes/conneticut
touch ~/.notes/delaware
touch ~/.notes/florida
touch ~/.notes/georgia
touch ~/.notes/hawaii
touch ~/.notes/idaho
touch ~/.notes/illinois
touch ~/.notes/indiana
touch ~/.notes/iowa
touch ~/.notes/kansas
touch ~/.notes/kentucky
touch ~/.notes/louisiana
touch ~/.notes/maine
touch ~/.notes/maryland
touch ~/.notes/massachusetts
touch ~/.notes/michigan
touch ~/.notes/minnesota
touch ~/.notes/mississippi
touch ~/.notes/missouri
touch ~/.notes/montana
touch ~/.notes/nebraska
touch ~/.notes/nevada
touch ~/.notes/new_hampshire
touch ~/.notes/new_jersey
touch ~/.notes/new_mexico
touch ~/.notes/new_york
touch ~/.notes/north_carolina
touch ~/.notes/north_dakota
touch ~/.notes/ohio
touch ~/.notes/oklahoma
touch ~/.notes/oregon
touch ~/.notes/pennsylvania
touch ~/.notes/rhode_island
touch ~/.notes/south_carolina
touch ~/.notes/south_dakota
touch ~/.notes/tennessee
touch ~/.notes/texas
touch ~/.notes/utah
touch ~/.notes/vermont
touch ~/.notes/virginia
touch ~/.notes/washington
touch ~/.notes/west_virginia
touch ~/.notes/wisconsin
touch ~/.notes/wyoming
