touch ~/.notes/alabama
touch ~/.notes/alaska
touch ~/.notes/arizona
touch ~/.notes/arkansas
touch ~/.notes/california
touch ~/.notes/colorado
touch ~/.notes/conneticut
touch ~/.notes/delaware
touch ~/.notes/florida
touch ~/.notes/georgia
touch ~/.notes/hawaii
touch ~/.notes/idaho
touch ~/.notes/illinois
touch ~/.notes/indiana
touch ~/.notes/iowa
touch ~/.notes/kansas
touch ~/.notes/kentucky
touch ~/.notes/louisiana
touch ~/.notes/maine
touch ~/.notes/maryland
touch ~/.notes/massachusetts
touch ~/.notes/michigan
touch ~/.notes/minnesota
touch ~/.notes/mississippi
touch ~/.notes/missouri
